### ISSUE TITLE
Add option to pass kernel_* and bias_* regularizers to Coral layer

### ISSUE THREAD

**Issue by gmgeorg** [ck37/coral-ordinal#17]
CORN layer inherits fromDense, so it all usual **kwargs can be passed.

Coral layer inherits from Layer, so kernel_regualizer/bias_regularizer (and other kwargs that would make sense for Coral) dont work as expected (passing them fails init since Layer does not recognized those kwarggs)

**Comment by ck37** [comment]
Should the Coral layer inherit from Dense instead of Layer?

-ck.mobile

**Comment by gmgeorg** [comment]
I don't think that will be as trivial, since the AFAIU the point of the CORAL layer is that it is a specific (constrained) structure of a fully connected dense layer (which is what CORN solves).

Looking at Dense() layer implementation, it should be straightforward to pass `kernel_regularizer` and `bias_regularizer` as arguments to the CoralOrdinalLayer init and then pass them to `self.add_weight(...)` for the kernel and bias respectively.  

See https://github.com/keras-team/keras/blob/v2.8.0/keras/layers/core/dense.py#L147

This is mostly to support the same function signagure as a typical Dense layer that has bias/kernel weights.

**Comment by ck37** [comment]
Belated response but thanks for the explanation on this!
