### ISSUE TITLE
Can you provide an example for functional API?

### ISSUE THREAD

**Issue by orko19** [ck37/coral-ordinal#2]
How to use coral_ordinal (CoralOrdinal, OrdinalCrossEntropy, MeanAbsoluteErrorLabels) with the functional API rather then sequential model?

**Comment by ck37** [comment]
No problem, added this to the MNIST example in the Colab notebook:
https://colab.research.google.com/drive/1AQl4XeqRRhd7l30bmgLVObKt5RFPHttn?#scrollTo=PAg-gWZED1mR

Cheers,
Chris

**Comment by ck37** [comment]
Oops, referenced the wrong issue in my commit - should have tagged #1
