### ISSUE TITLE
bug in Colab notebook's MNIST example

### ISSUE THREAD

**Issue by albertjiang** [ck37/coral-ordinal#6]
There is a bug in the MNIST example in the Colab notebook: 
shuffle() was called on test_dataset, but later you compared your prediction on the test dataset against the pre-shuffled mnist_labels_test. This is why the accuracy was only 10% (i.e. random), and the MAE computed doesn't match the one reported by evaluate(). 

A simple fix would be to remove shuffle() from test_dataset. After fix, the accuracy becomes 57% for labels and 67% for labels2. MAE(version 2) was close to what evaluate(test_dataset) was reporting (0.541 vs. 0.538). So there might still be some subtle differences between the two ways of computing them.

Thank you for making the code available!

**Comment by ck37** [comment]
Ah thanks a bunch, fixed!
